### ISSUE TITLE
Process crash due to concurrent map read and map write

### ISSUE THREAD

**Issue by chriswessels** [appleboy/gorush#145]
Hi there,

I'm running the appleboy/gorush image as a Docker container, and it seems to crash consistently every 500 minutes or so, with the following output:

```
INFO[2016/11/11 - 14:56:37] | header | GET /sys/stats 10.112.1.1  Go-http-client/1.1
fatal error: concurrent map read and map write
[GIN] 2016/11/11 - 14:56:37 | 200 |     115.691µs | 10.112.1.1 |   GET     /sys/stats

goroutine 2135 [running]:
runtime.throw(0xa49bd3, 0x21)
	/usr/local/go/src/runtime/panic.go:566 +0x95 fp=0xc4207b9080 sp=0xc4207b9060
runtime.mapaccess2(0x995200, 0xc4201ea9f0, 0xc420018990, 0xc4207b9110, 0xc4207b9110)
	/usr/local/go/src/runtime/hashmap.go:340 +0x249 fp=0xc4207b90c8 sp=0xc4207b9080
reflect.mapaccess(0x995200, 0xc4201ea9f0, 0xc420018990, 0xc4201ea9f0)
	/usr/local/go/src/runtime/hashmap.go:1008 +0x3f fp=0xc4207b9100 sp=0xc4207b90c8
reflect.Value.MapIndex(0x995200, 0xc42015c160, 0x195, 0x965760, 0xc420018990, 0x98, 0xc4207b91e8, 0x38, 0xa)
	/usr/local/go/src/reflect/value.go:1040 +0x128 fp=0xc4207b9188 sp=0xc4207b9100
encoding/json.(*mapEncoder).encode(0xc420206058, 0xc4200b2210, 0x995200, 0xc42015c160, 0x195, 0x100)
	/usr/local/go/src/encoding/json/encode.go:646 +0x4f0 fp=0xc4207b92e0 sp=0xc4207b9188
encoding/json.(*mapEncoder).(encoding/json.encode)-fm(0xc4200b2210, 0x995200, 0xc42015c160, 0x195, 0x100)
	/usr/local/go/src/encoding/json/encode.go:662 +0x64 fp=0xc4207b9320 sp=0xc4207b92e0
encoding/json.(*structEncoder).encode(0xc4207c65a0, 0xc4200b2210, 0xa1ad00, 0xc42015c120, 0x199, 0x100)
	/usr/local/go/src/encoding/json/encode.go:601 +0x253 fp=0xc4207b9480 sp=0xc4207b9320
encoding/json.(*structEncoder).(encoding/json.encode)-fm(0xc4200b2210, 0xa1ad00, 0xc42015c120, 0x199, 0xc420150100)
	/usr/local/go/src/encoding/json/encode.go:615 +0x64 fp=0xc4207b94c0 sp=0xc4207b9480
encoding/json.(*ptrEncoder).encode(0xc420206098, 0xc4200b2210, 0x9494a0, 0xc42015c120, 0x16, 0x940100)
	/usr/local/go/src/encoding/json/encode.go:742 +0xe3 fp=0xc4207b9500 sp=0xc4207b94c0
encoding/json.(*ptrEncoder).(encoding/json.encode)-fm(0xc4200b2210, 0x9494a0, 0xc42015c120, 0x16, 0xc420150100)
	/usr/local/go/src/encoding/json/encode.go:747 +0x64 fp=0xc4207b9540 sp=0xc4207b9500
encoding/json.(*encodeState).reflectValue(0xc4200b2210, 0x9494a0, 0xc42015c120, 0x16, 0x100)
	/usr/local/go/src/encoding/json/encode.go:307 +0x82 fp=0xc4207b9578 sp=0xc4207b9540
encoding/json.(*encodeState).marshal(0xc4200b2210, 0x9494a0, 0xc42015c120, 0xc4207b0100, 0x0, 0x0)
	/usr/local/go/src/encoding/json/encode.go:280 +0xb8 fp=0xc4207b95b0 sp=0xc4207b9578
encoding/json.(*Encoder).Encode(0xc4207b9668, 0x9494a0, 0xc42015c120, 0x7f492fefa2b8, 0xc4201ce000)
	/usr/local/go/src/encoding/json/stream.go:193 +0x8e fp=0xc4207b9640 sp=0xc4207b95b0
github.com/appleboy/gorush/vendor/github.com/gin-gonic/gin/render.WriteJSON(0x7f492fefa280, 0xc4201ce000, 0x9494a0, 0xc42015c120, 0xc4201ce000, 0x0)
	/go/src/github.com/appleboy/gorush/vendor/github.com/gin-gonic/gin/render/json.go:40 +0xf0 fp=0xc4207b96c8 sp=0xc4207b9640
github.com/appleboy/gorush/vendor/github.com/gin-gonic/gin.(*Context).JSON(0xc4201ce000, 0xc8, 0x9494a0, 0xc42015c120)
	/go/src/github.com/appleboy/gorush/vendor/github.com/gin-gonic/gin/context.go:419 +0x8c fp=0xc4207b9708 sp=0xc4207b96c8
github.com/appleboy/gorush/gorush.sysStatsHandler(0xc4201ce000)
	/go/src/github.com/appleboy/gorush/gorush/status.go:83 +0x5a fp=0xc4207b9738 sp=0xc4207b9708
github.com/appleboy/gorush/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc4201ce000)
	/go/src/github.com/appleboy/gorush/vendor/github.com/gin-gonic/gin/context.go:97 +0x5a fp=0xc4207b9758 sp=0xc4207b9738
github.com/appleboy/gorush/gorush.StatMiddleware.func1(0xc4201ce000)
	/go/src/github.com/appleboy/gorush/gorush/status.go:90 +0xaa fp=0xc4207b97d0 sp=0xc4207b9758
github.com/appleboy/gorush/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc4201ce000)
	/go/src/github.com/appleboy/gorush/vendor/github.com/gin-gonic/gin/context.go:97 +0x5a fp=0xc4207b97f0 sp=0xc4207b97d0
github.com/appleboy/gorush/gorush.LogMiddleware.func1(0xc4201ce000)
	/go/src/github.com/appleboy/gorush/gorush/log.go:262 +0x121 fp=0xc4207b9870 sp=0xc4207b97f0
github.com/appleboy/gorush/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc4201ce000)
	/go/src/github.com/appleboy/gorush/vendor/github.com/gin-gonic/gin/context.go:97 +0x5a fp=0xc4207b9890 sp=0xc4207b9870
github.com/appleboy/gorush/gorush.VersionMiddleware.func1(0xc4201ce000)
	/go/src/github.com/appleboy/gorush/gorush/version.go:35 +0xc1 fp=0xc4207b98e0 sp=0xc4207b9890
github.com/appleboy/gorush/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc4201ce000)
	/go/src/github.com/appleboy/gorush/vendor/github.com/gin-gonic/gin/context.go:97 +0x5a fp=0xc4207b9900 sp=0xc4207b98e0
github.com/appleboy/gorush/vendor/github.com/gin-gonic/gin.RecoveryWithWriter.func1(0xc4201ce000)
	/go/src/github.com/appleboy/gorush/vendor/github.com/gin-gonic/gin/recovery.go:45 +0x5a fp=0xc4207b9930 sp=0xc4207b9900
github.com/appleboy/gorush/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc4201ce000)
	/go/src/github.com/appleboy/gorush/vendor/github.com/gin-gonic/gin/context.go:97 +0x5a fp=0xc4207b9950 sp=0xc4207b9930
github.com/appleboy/gorush/vendor/github.com/gin-gonic/gin.LoggerWithWriter.func1(0xc4201ce000)
	/go/src/github.com/appleboy/gorush/vendor/github.com/gin-gonic/gin/logger.go:63 +0xa7 fp=0xc4207b9b90 sp=0xc4207b9950
github.com/appleboy/gorush/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc4201ce000)
	/go/src/github.com/appleboy/gorush/vendor/github.com/gin-gonic/gin/context.go:97 +0x5a fp=0xc4207b9bb0 sp=0xc4207b9b90
github.com/appleboy/gorush/vendor/github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc4207ba0e0, 0xc4201ce000)
	/go/src/github.com/appleboy/gorush/vendor/github.com/gin-gonic/gin/gin.go:284 +0x64e fp=0xc4207b9ca8 sp=0xc4207b9bb0
github.com/appleboy/gorush/vendor/github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc4207ba0e0, 0xd14260, 0xc42006e0d0, 0xc420130000)
	/go/src/github.com/appleboy/gorush/vendor/github.com/gin-gonic/gin/gin.go:265 +0x130 fp=0xc4207b9ce0 sp=0xc4207b9ca8
net/http.serverHandler.ServeHTTP(0xc4207ca0d0, 0xd14260, 0xc42006e0d0, 0xc420130000)
	/usr/local/go/src/net/http/server.go:2202 +0x7d fp=0xc4207b9d28 sp=0xc4207b9ce0
net/http.(*conn).serve(0xc420170300, 0xd14c20, 0xc420016940)
	/usr/local/go/src/net/http/server.go:1579 +0x4b7 fp=0xc4207b9f88 sp=0xc4207b9d28
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc4207b9f90 sp=0xc4207b9f88
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2293 +0x44d

goroutine 1 [IO wait]:
net.runtime_pollWait(0x7f492fcba700, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc4207da060, 0x72, 0xc42014ce38, 0xc420018018)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc4207da060, 0xd110a0, 0xc420018018)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).accept(0xc4207da000, 0x0, 0xd0f4e0, 0xc420230480)
	/usr/local/go/src/net/fd_unix.go:419 +0x238
net.(*TCPListener).accept(0xc4207c0060, 0x60, 0x78, 0xc420170380)
	/usr/local/go/src/net/tcpsock_posix.go:132 +0x2e
net.(*TCPListener).AcceptTCP(0xc4207c0060, 0x1, 0xc42014cf60, 0x410928)
	/usr/local/go/src/net/tcpsock.go:209 +0x49
github.com/appleboy/gorush/vendor/github.com/fvbock/endless.(*endlessListener).Accept(0xc4207be100, 0xa84b40, 0xc420170380, 0xd14ce0, 0xc4207c62d0)
	/go/src/github.com/appleboy/gorush/vendor/github.com/fvbock/endless/endless.go:490 +0x4f
net/http.(*Server).Serve(0xc4207ca0d0, 0xd13da0, 0xc4207be100, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2273 +0x1ce
github.com/appleboy/gorush/vendor/github.com/fvbock/endless.(*endlessServer).Serve(0xc4207ca0d0, 0x0, 0x0)
	/go/src/github.com/appleboy/gorush/vendor/github.com/fvbock/endless/endless.go:195 +0x194
github.com/appleboy/gorush/vendor/github.com/fvbock/endless.(*endlessServer).ListenAndServe(0xc4207ca0d0, 0x5, 0xd0e060)
	/go/src/github.com/appleboy/gorush/vendor/github.com/fvbock/endless/endless.go:229 +0x225
github.com/appleboy/gorush/vendor/github.com/fvbock/endless.ListenAndServe(0xc4207bc1c0, 0x5, 0xd0e060, 0xc4207ba0e0, 0x4, 0xc4207bc1c0)
	/go/src/github.com/appleboy/gorush/vendor/github.com/fvbock/endless/endless.go:153 +0x57
github.com/appleboy/gorush/gorush.RunHTTPServer(0x8, 0x2000)
	/go/src/github.com/appleboy/gorush/gorush/server.go:91 +0xbe
main.main()
	/go/src/github.com/appleboy/gorush/gorush.go:248 +0xca8

goroutine 5 [syscall, 525 minutes]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x157
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 6 [sleep]:
time.Sleep(0x3b9aca00)
	/usr/local/go/src/runtime/time.go:59 +0xe1
github.com/appleboy/gorush/vendor/github.com/thoas/stats.New.func1(0xc42006d020)
	/go/src/github.com/appleboy/gorush/vendor/github.com/thoas/stats/stats.go:33 +0x38
created by github.com/appleboy/gorush/vendor/github.com/thoas/stats.New
	/go/src/github.com/appleboy/gorush/vendor/github.com/thoas/stats/stats.go:35 +0x169

goroutine 11 [chan receive, 525 minutes]:
github.com/appleboy/gorush/gorush.startWorker()
	/go/src/github.com/appleboy/gorush/gorush/notification.go:200 +0x85
created by github.com/appleboy/gorush/gorush.InitWorkers
	/go/src/github.com/appleboy/gorush/gorush/notification.go:194 +0x201

goroutine 12 [chan receive, 525 minutes]:
github.com/appleboy/gorush/gorush.startWorker()
	/go/src/github.com/appleboy/gorush/gorush/notification.go:200 +0x85
created by github.com/appleboy/gorush/gorush.InitWorkers
	/go/src/github.com/appleboy/gorush/gorush/notification.go:194 +0x201

goroutine 13 [chan receive, 525 minutes]:
github.com/appleboy/gorush/gorush.startWorker()
	/go/src/github.com/appleboy/gorush/gorush/notification.go:200 +0x85
created by github.com/appleboy/gorush/gorush.InitWorkers
	/go/src/github.com/appleboy/gorush/gorush/notification.go:194 +0x201

goroutine 14 [chan receive, 525 minutes]:
github.com/appleboy/gorush/gorush.startWorker()
	/go/src/github.com/appleboy/gorush/gorush/notification.go:200 +0x85
created by github.com/appleboy/gorush/gorush.InitWorkers
	/go/src/github.com/appleboy/gorush/gorush/notification.go:194 +0x201

goroutine 15 [chan receive, 525 minutes]:
github.com/appleboy/gorush/gorush.startWorker()
	/go/src/github.com/appleboy/gorush/gorush/notification.go:200 +0x85
created by github.com/appleboy/gorush/gorush.InitWorkers
	/go/src/github.com/appleboy/gorush/gorush/notification.go:194 +0x201

goroutine 16 [chan receive, 525 minutes]:
github.com/appleboy/gorush/gorush.startWorker()
	/go/src/github.com/appleboy/gorush/gorush/notification.go:200 +0x85
created by github.com/appleboy/gorush/gorush.InitWorkers
	/go/src/github.com/appleboy/gorush/gorush/notification.go:194 +0x201

goroutine 33 [chan receive, 525 minutes]:
github.com/appleboy/gorush/gorush.startWorker()
	/go/src/github.com/appleboy/gorush/gorush/notification.go:200 +0x85
created by github.com/appleboy/gorush/gorush.InitWorkers
	/go/src/github.com/appleboy/gorush/gorush/notification.go:194 +0x201

goroutine 34 [chan receive, 525 minutes]:
github.com/appleboy/gorush/gorush.startWorker()
	/go/src/github.com/appleboy/gorush/gorush/notification.go:200 +0x85
created by github.com/appleboy/gorush/gorush.InitWorkers
	/go/src/github.com/appleboy/gorush/gorush/notification.go:194 +0x201

goroutine 49 [chan receive, 525 minutes]:
github.com/appleboy/gorush/vendor/github.com/fvbock/endless.(*endlessServer).handleSignals(0xc4207ca0d0)
	/go/src/github.com/appleboy/gorush/vendor/github.com/fvbock/endless/endless.go:326 +0xeb
created by github.com/appleboy/gorush/vendor/github.com/fvbock/endless.(*endlessServer).ListenAndServe
	/go/src/github.com/appleboy/gorush/vendor/github.com/fvbock/endless/endless.go:213 +0x7c

goroutine 65 [select, 525 minutes, locked to thread]:
runtime.gopark(0xa85180, 0x0, 0xa389fa, 0x6, 0x18, 0x2)
	/usr/local/go/src/runtime/proc.go:259 +0x13a
runtime.selectgoImpl(0xc4207d6730, 0x0, 0x18)
	/usr/local/go/src/runtime/select.go:423 +0x11d9
runtime.selectgo(0xc4207d6730)
	/usr/local/go/src/runtime/select.go:238 +0x1c
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal1_unix.go:304 +0x2f3
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1

goroutine 2136 [runnable]:
syscall.Syscall(0x3, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.Close(0x6, 0x1, 0x0)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:296 +0x4a
net.(*netFD).destroy(0xc420174690)
	/usr/local/go/src/net/fd_unix.go:187 +0x4a
net.(*netFD).decref(0xc420174690)
	/usr/local/go/src/net/fd_mutex.go:211 +0x4e
net.(*netFD).Close(0xc420174690, 0x4ccce2, 0xd38820)
	/usr/local/go/src/net/fd_unix.go:202 +0x5a
net.(*conn).Close(0xc4207c0028, 0x0, 0x0)
	/usr/local/go/src/net/net.go:197 +0x4c
github.com/appleboy/gorush/vendor/github.com/fvbock/endless.endlessConn.Close(0xd17a00, 0xc4207c0028, 0xc4207ca0d0, 0xc4207e1200, 0x0)
	/go/src/github.com/appleboy/gorush/vendor/github.com/fvbock/endless/endless.go:538 +0x31
github.com/appleboy/gorush/vendor/github.com/fvbock/endless.(*endlessConn).Close(0xc420230460, 0xc4201703e8, 0xc4201703e8)
	<autogenerated>:21 +0x64
net/http.(*conn).close(0xc420170380)
	/usr/local/go/src/net/http/server.go:1427 +0x42
net/http.(*conn).serve.func1(0xc420170380)
	/usr/local/go/src/net/http/server.go:1495 +0xa9
net/http.(*conn).serve(0xc420170380, 0xd14c20, 0xc4207e1240)
	/usr/local/go/src/net/http/server.go:1589 +0x564
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2293 +0x44d
```

Any ideas?

Thanks

**Comment by appleboy** [comment]
@chriswessels Can you help to try the latest version. https://github.com/appleboy/gorush/releases/tag/v1.7.2

**Comment by chriswessels** [comment]
@appleboy Now running 1.7.3, will let you know if there are any further issues! Thanks :)

**Comment by appleboy** [comment]
@chriswessels Thanks.
