### ISSUE TITLE
Segmentation fault in boltdb

### ISSUE THREAD

**Issue by hellais** [appleboy/gorush#239]
It seems like my gorush instance fails with a segmentation fault in boltdb related code. It happens right after I trigger a notification to a iOS device.
I suspect it's happening because the permissions to access the `bolt.db` database file are not correct. When I change the permissions back I am able to send notifications correctly.

Here is the stacktrace of the error:

```
Jun 22 15:06:48 notify gorush[3824]: panic: runtime error: invalid memory address or nil pointer dereference
Jun 22 15:06:48 notify gorush[3824]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x9eb916]
Jun 22 15:06:48 notify gorush[3824]: goroutine 13 [running]:
Jun 22 15:06:48 notify gorush[3824]: github.com/appleboy/gorush/vendor/github.com/asdine/storm.(*DB).Get(0x0, 0xc4201b70da, 0x6, 0xb7b660, 0xc4209873b0, 0xb52bc0, 0xc4209873a0, 0xc420988ba0, 0xc4201191d8)
Jun 22 15:06:48 notify gorush[3824]: /srv/app/src/github.com/appleboy/gorush/vendor/github.com/asdine/storm/storm.go:142 +0x26
Jun 22 15:06:48 notify gorush[3824]: github.com/appleboy/gorush/storage/boltdb.(*Storage).getBoltDB(0xc4201778c0, 0xcc47ef, 0x18, 0xc4209873a0)
Jun 22 15:06:48 notify gorush[3824]: /srv/app/src/github.com/appleboy/gorush/storage/boltdb/boltdb.go:51 +0x10d
Jun 22 15:06:48 notify gorush[3824]: github.com/appleboy/gorush/storage/boltdb.(*Storage).GetIosSuccess(0xc4201778c0, 0xc42097ec40)
Jun 22 15:06:48 notify gorush[3824]: /srv/app/src/github.com/appleboy/gorush/storage/boltdb/boltdb.go:96 +0x66
Jun 22 15:06:48 notify gorush[3824]: github.com/appleboy/gorush/storage/boltdb.(*Storage).AddIosSuccess(0xc4201778c0, 0x1)
Jun 22 15:06:48 notify gorush[3824]: /srv/app/src/github.com/appleboy/gorush/storage/boltdb/boltdb.go:63 +0x2b
Jun 22 15:06:48 notify gorush[3824]: github.com/appleboy/gorush/gorush.PushToIOS(0xc42003c780, 0x1, 0x4, 0x1, 0xc4200ec760, 0x14, 0x0, 0x0, 0x0, 0x0, ...)
Jun 22 15:06:48 notify gorush[3824]: /srv/app/src/github.com/appleboy/gorush/gorush/notification.go:442 +0x76a
Jun 22 15:06:48 notify gorush[3824]: github.com/appleboy/gorush/gorush.startWorker()
Jun 22 15:06:48 notify gorush[3824]: /srv/app/src/github.com/appleboy/gorush/gorush/notification.go:231 +0x104
Jun 22 15:06:48 notify gorush[3824]: created by github.com/appleboy/gorush/gorush.InitWorkers
Jun 22 15:06:48 notify gorush[3824]: /srv/app/src/github.com/appleboy/gorush/gorush/notification.go:222 +0x1da
Jun 22 15:06:48 notify systemd[1]: gorush.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Jun 22 15:06:48 notify systemd[1]: Unit gorush.service entered failed state.
```

**Comment by appleboy** [comment]
@hellais Do you have the same problem on this?

**Comment by hellais** [comment]
@appleboy yes this issue is still occurring and actually it also happens in leveldb.

See:
```
```Jul 19 16:37:12 notify gorush[21334]: panic: runtime error: invalid memory address or nil pointer derefer
ence
Jul 19 16:37:12 notify gorush[21334]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x168 pc=0xa8
d235]
Jul 19 16:37:12 notify gorush[21334]: goroutine 519 [running]:
Jul 19 16:37:12 notify gorush[21334]: github.com/appleboy/gorush/vendor/github.com/syndtr/goleveldb/level
db.(*DB).isClosed(0x0, 0xc4207b76e0)
Jul 19 16:37:12 notify gorush[21334]: /srv/app/src/github.com/appleboy/gorush/vendor/github.com/syndtr/go
leveldb/leveldb/db_state.go:225 +0x5
Jul 19 16:37:12 notify gorush[21334]: github.com/appleboy/gorush/vendor/github.com/syndtr/goleveldb/level
db.(*DB).ok(0x0, 0x4, 0xc420035df0)
Jul 19 16:37:12 notify gorush[21334]: /srv/app/src/github.com/appleboy/gorush/vendor/github.com/syndtr/go
leveldb/leveldb/db_state.go:230 +0x2b
Jul 19 16:37:12 notify gorush[21334]: github.com/appleboy/gorush/vendor/github.com/syndtr/goleveldb/level
db.(*DB).Get(0x0, 0xc420035e50, 0x12, 0x20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
Jul 19 16:37:12 notify gorush[21334]: /srv/app/src/github.com/appleboy/gorush/vendor/github.com/syndtr/go
leveldb/leveldb/db.go:835 +0xa0
Jul 19 16:37:12 notify gorush[21334]: github.com/appleboy/gorush/storage/leveldb.getLevelDB(0xcc08d6, 0x1
2, 0xc420035ea0)
Jul 19 16:37:12 notify gorush[21334]: /srv/app/src/github.com/appleboy/gorush/storage/leveldb/leveldb.go:
34 +0xb0
Jul 19 16:37:12 notify gorush[21334]: github.com/appleboy/gorush/storage/leveldb.(*Storage).GetTotalCount
(0xc42017f8c0, 0xc4215fc7e0)
Jul 19 16:37:12 notify gorush[21334]: /srv/app/src/github.com/appleboy/gorush/storage/leveldb/leveldb.go:
100 +0x49
Jul 19 16:37:12 notify gorush[21334]: github.com/appleboy/gorush/gorush.Metrics.Collect(0xc4201bf110, 0xc
4201bf180, 0xc4201bf1f0, 0xc4201bf260, 0xc4201bf2d0, 0xc42129cd20)
Jul 19 16:37:12 notify gorush[21334]: /srv/app/src/github.com/appleboy/gorush/gorush/metrics.go:65 +0x47
Jul 19 16:37:12 notify gorush[21334]: github.com/appleboy/gorush/gorush.(*Metrics).Collect(0xc4201b8d20,
0xc42129cd20)
Jul 19 16:37:12 notify gorush[21334]: <autogenerated>:2 +0x73
Jul 19 16:37:12 notify gorush[21334]: github.com/appleboy/gorush/vendor/github.com/prometheus/client_gola
ng/prometheus.(*Registry).Gather.func2(0xc42166c350, 0xc42129cd20, 0x1071b40, 0xc4201b8d20)
Jul 19 16:37:12 notify gorush[21334]: /srv/app/src/github.com/appleboy/gorush/vendor/github.com/prometheu
s/client_golang/prometheus/registry.go:382 +0x61
Jul 19 16:37:12 notify gorush[21334]: created by github.com/appleboy/gorush/vendor/github.com/prometheus/
client_golang/prometheus.(*Registry).Gather
Jul 19 16:37:12 notify gorush[21334]: /srv/app/src/github.com/appleboy/gorush/vendor/github.com/prometheu
s/client_golang/prometheus/registry.go:383 +0x2ec
```

**Comment by appleboy** [comment]
@hellais So you can change the levelDB permission to fix this problem?

**Comment by hellais** [comment]
@appleboy I actually ended up just dropping the disk based storage backend and just relying on `memory` based storage.

I think that the right fix for this would probably be to check when gorush starts if everything is ok with the storage backends, so that at least some exception is thrown on boot rather than at runtime.

**Comment by appleboy** [comment]
@hellais I will check the file permission before start the daemon.

**Comment by hellais** [comment]
> @hellais I will check the file permission before starting the daemon.

That seems like a good idea. Even better if you try to do some operation similar to the one that is done when a push notification is done (maybe write a value and remove it) to check that it actually works as expected.

**Comment by slimus** [comment]
@hellais @appleboy is it actual yet?

**Comment by appleboy** [comment]
@slimus I can't reproduce the issue.
