### ISSUE TITLE
Runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by karpoffS** [appleboy/gorush#455]
```
gorush | panic: runtime error: invalid memory address or nil pointer dereference
gorush | [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xb16740]
gorush |
gorush | goroutine 11 [running]:
gorush | sync.(*RWMutex).RLock(...)
gorush | 	/usr/local/go/src/sync/rwmutex.go:48
gorush | github.com/tidwall/buntdb.(*Tx).lock(0xc000bac3a0)
gorush | 	/go/pkg/mod/github.com/tidwall/buntdb@v1.1.0/buntdb.go:1090 +0x30
gorush | github.com/tidwall/buntdb.(*DB).Begin(0x0, 0x1612100, 0x0, 0xc000032520, 0xc00090aa40)
gorush | 	/go/pkg/mod/github.com/tidwall/buntdb@v1.1.0/buntdb.go:1067 +0x61
gorush | github.com/tidwall/buntdb.(*DB).managed(0x0, 0x0, 0xc00090aab8, 0x0, 0x0)
gorush | 	/go/pkg/mod/github.com/tidwall/buntdb@v1.1.0/buntdb.go:939 +0x57
gorush | github.com/tidwall/buntdb.(*DB).View(...)
gorush | 	/go/pkg/mod/github.com/tidwall/buntdb@v1.1.0/buntdb.go:972
gorush | github.com/appleboy/gorush/storage/buntdb.(*Storage).getBuntDB(0xc00021c600, 0xe74a3e, 0x1c, 0xc00090ab28)
gorush | 	/drone/src/storage/buntdb/buntdb.go:65 +0xb8
gorush | github.com/appleboy/gorush/storage/buntdb.(*Storage).GetAndroidSuccess(...)
gorush | 	/drone/src/storage/buntdb/buntdb.go:140
gorush | github.com/appleboy/gorush/storage/buntdb.(*Storage).AddAndroidSuccess(0xc00021c600, 0x0)
gorush | 	/drone/src/storage/buntdb/buntdb.go:103 +0x57
gorush | github.com/appleboy/gorush/gorush.PushToAndroid(0x0, 0x0, 0xc0001d0820, 0xc, 0xd, 0x2, 0xc00008e420, 0x56, 0x0, 0x0, ...)
gorush | 	/drone/src/gorush/notification_fcm.go:134 +0x381
gorush | github.com/appleboy/gorush/gorush.SendNotification(0x0, 0x0, 0xc0001d0820, 0xc, 0xd, 0x2, 0xc00008e420, 0x56, 0x0, 0x0, ...)
gorush | 	/drone/src/gorush/worker.go:22 +0x79
gorush | github.com/appleboy/gorush/gorush.startWorker()
gorush | 	/drone/src/gorush/worker.go:29 +0xb3
gorush | created by github.com/appleboy/gorush/gorush.InitWorkers
gorush | 	/drone/src/gorush/worker.go:12 +0x151
```

**Comment by appleboy** [comment]
Please give more detail information like what is your command?

**Comment by appleboy** [comment]
@karpoffS Can't reproduce the problem and please reopen if you can give more detail information.

Please try the latest version.
