### ISSUE TITLE
Kubernetes deploy fail

### ISSUE THREAD

**Issue by tetra12** [appleboy/gorush#555]
Hello

I'm trying to deploy Gorush v.1.13.0, but getting the following error on a pod start, pls find details below.
System
Ubuntu 20.04.1
Kubernetes: 1.20.1
Gorush: 1.13.0

```bash
{"level":"info","msg":"Init App Status Engine as redis","time":"2021-01-08T21:33:29Z"}
{"level":"info","msg":"worker number is 8, queue number is 8192","time":"2021-01-08T21:33:29Z"}
panic: refresh token fail

goroutine 1 [running]:
github.com/appleboy/gorush/gorush.GetPushClient.func1()
	/drone/src/gorush/notification_hms.go:25 +0xa9
sync.(*Once).doSlow(0x17c2590, 0xc000b0eed8)
	/usr/local/go/src/sync/once.go:66 +0xec
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:57
github.com/appleboy/gorush/gorush.GetPushClient(0xc000b0ef18, 0xc00003b9f0, 0xb, 0xd3ae01)
	/drone/src/gorush/notification_hms.go:22 +0x91
github.com/appleboy/gorush/gorush.InitHMSClient(0xc00003b9e0, 0xc, 0xc00003b9f0, 0xb, 0x0, 0x1e, 0xc00003b730)
	/drone/src/gorush/notification_hms.go:57 +0x158
main.main()
	/drone/src/main.go:337 +0x2109
```
Pls let me know if you need more info on this bug.

Thanks for building Gorush !

**Comment by keremoge** [comment]
related to #582
